# -*- coding: utf-8 -*-
"""Lab_1_(b)_E20CSE119_Hansika Sachdeva_EB09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H34Q1PlLBUfJ3vrWb8c4olxRLCbCE6O_

**IMPORTING LIBRARIES**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

"""**UPLOADING FILE**"""

from google.colab import files
uploaded=files.upload()

df=pd.read_csv("/content/mushrom (1).csv")
df.info()

print(df.head())

"""**GIVING COLUMN NAMES**"""

df.columns=['A','B',"C","D","E",'F','G',"H","I","J","K","L","M","N","O","P","Q","R","S","T","U"]
df

"""**Checking if it has null values or not**"""

print(df.isnull())

print(df.isnull().sum())

"""**THIS DATASET DOES NOT HAVE ANY NULL VALE**"""

print(df.shape)

print(df.isna())

"""**Finding Mean**"""

print(df.mean())

"""**Median** """

print(df.median())

"""**Mode**"""

from scipy import stats
print(df.mode())

"""**Variance** """

import statistics
df.var()

"""**Standard Deviation**"""

print(df.std()) # numpy

import statistics
statistics.stdev(df["A"])

"""**Normal Distribution**"""

from numpy.linalg import norm 
print(norm(df['A']))
print(norm(df['B']))
print(norm(df['C']))

"""**Uniform Distribution**"""

from scipy.stats import uniform 
print(np.random.uniform(df['A']))
print("\n")
print(np.random.uniform(df['B']))
print("\n")
print(np.random.uniform(df['C']))
print("\n")
print(np.random.uniform(df['D']))
print("\n")
print(np.random.uniform(df['E']))
print("\n")
print(np.random.uniform(df['F']))
print("\n")
print(np.random.uniform(df['G']))
print("\n")
print(np.random.uniform(df['H']))
print("\n")
print(np.random.uniform(df['I']))
print("\n")
print(np.random.uniform(df['J']))
print("\n")
print(np.random.uniform(df['K']))
print("\n")
print(np.random.uniform(df['L']))

"""**PLOTS**

**DENSITY PLOT**
"""

df.plot(kind='density',subplots=True,sharex=False,figsize=(10,8))

"""# Bar Diagrams"""

sns.boxplot(data=df,palette='Set3')

"""# HISTOGRM"""

df.hist(alpha=.8, figsize=(10,8))

"""# DENSITY PLOT"""

df.plot(kind='density',subplots=True,sharex=False,figsize=(10,8))

"""**BOX PLOT**"""

sns.boxplot(df.A)

sns.boxplot(df.B)

sns.boxplot(df.C)

sns.boxplot(df.D)

sns.boxplot(df.E)

"""#LINE CHART"""

import matplotlib.pyplot as plot
df.plot.line(y="A")

import matplotlib.pyplot as plot
df.plot.line(y="B")

import matplotlib.pyplot as plot
df.plot.line(y="C")

import matplotlib.pyplot as plot
df.plot.line(y="E")

import matplotlib.pyplot as plot
df.plot.line(y="D")

"""# OUTLIERS"""

lowerLimit=df["A"].quantile(0.05)
lowerLimit

upperLimit=df["A"].quantile(0.95)
upperLimit

df[df["A"]<lowerLimit]

df[df["A"]>upperLimit]

df=df.astype('float64')
print(df)